export const clerkAppearance = {
  variables: {
    colorBackground: '#16161f',
    colorInputBackground: '#1e1e2d',
    colorText: '#f1f5f9',
    colorTextSecondary: '#94a3b8',
    colorTextOnPrimaryBackground: '#ffffff',
    colorInputText: '#f1f5f9',
    colorPrimary: '#6366f1',
    colorDanger: '#f87171',
    colorSuccess: '#34d399',
    borderRadius: '0.625rem',
    fontFamily: 'inherit',
    fontSize: '0.875rem',
  },
  elements: {
    card: 'border border-white/10 shadow-2xl',
    headerTitle: 'text-white font-bold',
    headerSubtitle: 'text-slate-400',
    socialButtonsBlockButton: 'border border-white/15 hover:border-white/30 hover:bg-white/5 transition-colors',
    socialButtonsBlockButtonText: 'text-slate-200 font-medium',
    socialButtonsBlockButtonArrow: 'text-slate-400',
    dividerLine: 'bg-white/10',
    dividerText: 'text-slate-500',
    formFieldLabel: 'text-slate-300 font-medium',
    formFieldInput: 'border border-white/15 text-white placeholder:text-slate-600 focus:border-indigo-500 focus:ring-indigo-500/20',
    formFieldInputShowPasswordButton: 'text-slate-400 hover:text-slate-200',
    formButtonPrimary: 'bg-indigo-600 hover:bg-indigo-500 text-white font-semibold transition-colors shadow-lg',
    footerActionLink: 'text-indigo-400 hover:text-indigo-300 font-semibold',
    identityPreviewText: 'text-slate-200',
    identityPreviewEditButtonIcon: 'text-slate-400',
    formFieldSuccessText: 'text-emerald-400',
    formFieldErrorText: 'text-red-400',
    alertText: 'text-slate-300',
    otpCodeFieldInput: 'border border-white/15 text-white',
  },
}
