export const clerkAppearance = {
  variables: {
    colorBackground: '#ffffff',
    colorInputBackground: '#f8fafc',
    colorText: '#0f172a',
    colorTextSecondary: '#64748b',
    colorTextOnPrimaryBackground: '#ffffff',
    colorInputText: '#0f172a',
    colorPrimary: '#6366f1',
    colorDanger: '#ef4444',
    colorSuccess: '#10b981',
    borderRadius: '0.625rem',
    fontFamily: 'inherit',
    fontSize: '0.875rem',
  },
  elements: {
    card: 'shadow-2xl',
    headerTitle: 'text-slate-900 font-bold',
    headerSubtitle: 'text-slate-500',
    socialButtonsBlockButton: 'border border-slate-200 hover:border-slate-300 hover:bg-slate-50 transition-colors',
    socialButtonsBlockButtonText: 'text-slate-700 font-medium',
    dividerLine: 'bg-slate-200',
    dividerText: 'text-slate-400',
    formFieldLabel: 'text-slate-700 font-medium',
    formFieldInput: 'border border-slate-300 text-slate-900 bg-slate-50 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20',
    formButtonPrimary: 'bg-indigo-600 hover:bg-indigo-700 text-white font-semibold shadow-md transition-colors',
    footerActionLink: 'text-indigo-600 hover:text-indigo-700 font-semibold',
    footerActionText: 'text-slate-500',
    identityPreviewText: 'text-slate-700',
    otpCodeFieldInput: 'border border-slate-300 text-slate-900',
    formFieldErrorText: 'text-red-600',
    formFieldSuccessText: 'text-emerald-600',
    alertText: 'text-slate-700',
  },
}
