// AUTO-GENERATED city taxonomy for programmatic SEO. Edit the generator, not this file.
export interface City {
  slug: string
  name: string
  region: string
  dept: string
}

export const CITIES: City[] = [
  { slug: "paris", name: "Paris", region: "\u00cele-de-France", dept: "75" },
  { slug: "marseille", name: "Marseille", region: "Provence-Alpes-C\u00f4te d'Azur", dept: "13" },
  { slug: "lyon", name: "Lyon", region: "Auvergne-Rh\u00f4ne-Alpes", dept: "69" },
  { slug: "toulouse", name: "Toulouse", region: "Occitanie", dept: "31" },
  { slug: "nice", name: "Nice", region: "Provence-Alpes-C\u00f4te d'Azur", dept: "06" },
  { slug: "nantes", name: "Nantes", region: "Pays de la Loire", dept: "44" },
  { slug: "montpellier", name: "Montpellier", region: "Occitanie", dept: "34" },
  { slug: "strasbourg", name: "Strasbourg", region: "Grand Est", dept: "67" },
  { slug: "bordeaux", name: "Bordeaux", region: "Nouvelle-Aquitaine", dept: "33" },
  { slug: "lille", name: "Lille", region: "Hauts-de-France", dept: "59" },
  { slug: "rennes", name: "Rennes", region: "Bretagne", dept: "35" },
  { slug: "reims", name: "Reims", region: "Grand Est", dept: "51" },
  { slug: "saint-etienne", name: "Saint-\u00c9tienne", region: "Auvergne-Rh\u00f4ne-Alpes", dept: "42" },
  { slug: "le-havre", name: "Le Havre", region: "Normandie", dept: "76" },
  { slug: "toulon", name: "Toulon", region: "Provence-Alpes-C\u00f4te d'Azur", dept: "83" },
  { slug: "grenoble", name: "Grenoble", region: "Auvergne-Rh\u00f4ne-Alpes", dept: "38" },
  { slug: "dijon", name: "Dijon", region: "Bourgogne-Franche-Comt\u00e9", dept: "21" },
  { slug: "angers", name: "Angers", region: "Pays de la Loire", dept: "49" },
  { slug: "nimes", name: "N\u00eemes", region: "Occitanie", dept: "30" },
  { slug: "villeurbanne", name: "Villeurbanne", region: "Auvergne-Rh\u00f4ne-Alpes", dept: "69" },
  { slug: "clermont-ferrand", name: "Clermont-Ferrand", region: "Auvergne-Rh\u00f4ne-Alpes", dept: "63" },
  { slug: "le-mans", name: "Le Mans", region: "Pays de la Loire", dept: "72" },
  { slug: "aix-en-provence", name: "Aix-en-Provence", region: "Provence-Alpes-C\u00f4te d'Azur", dept: "13" },
  { slug: "brest", name: "Brest", region: "Bretagne", dept: "29" },
  { slug: "tours", name: "Tours", region: "Centre-Val de Loire", dept: "37" },
  { slug: "amiens", name: "Amiens", region: "Hauts-de-France", dept: "80" },
  { slug: "limoges", name: "Limoges", region: "Nouvelle-Aquitaine", dept: "87" },
  { slug: "annecy", name: "Annecy", region: "Auvergne-Rh\u00f4ne-Alpes", dept: "74" },
  { slug: "perpignan", name: "Perpignan", region: "Occitanie", dept: "66" },
  { slug: "boulogne-billancourt", name: "Boulogne-Billancourt", region: "\u00cele-de-France", dept: "92" },
  { slug: "metz", name: "Metz", region: "Grand Est", dept: "57" },
  { slug: "besancon", name: "Besan\u00e7on", region: "Bourgogne-Franche-Comt\u00e9", dept: "25" },
  { slug: "orleans", name: "Orl\u00e9ans", region: "Centre-Val de Loire", dept: "45" },
  { slug: "saint-denis", name: "Saint-Denis", region: "\u00cele-de-France", dept: "93" },
  { slug: "rouen", name: "Rouen", region: "Normandie", dept: "76" },
  { slug: "mulhouse", name: "Mulhouse", region: "Grand Est", dept: "68" },
  { slug: "caen", name: "Caen", region: "Normandie", dept: "14" },
  { slug: "nancy", name: "Nancy", region: "Grand Est", dept: "54" },
  { slug: "argenteuil", name: "Argenteuil", region: "\u00cele-de-France", dept: "95" },
  { slug: "montreuil", name: "Montreuil", region: "\u00cele-de-France", dept: "93" },
  { slug: "roubaix", name: "Roubaix", region: "Hauts-de-France", dept: "59" },
  { slug: "tourcoing", name: "Tourcoing", region: "Hauts-de-France", dept: "59" },
  { slug: "nanterre", name: "Nanterre", region: "\u00cele-de-France", dept: "92" },
  { slug: "avignon", name: "Avignon", region: "Provence-Alpes-C\u00f4te d'Azur", dept: "84" },
  { slug: "creteil", name: "Cr\u00e9teil", region: "\u00cele-de-France", dept: "94" },
  { slug: "dunkerque", name: "Dunkerque", region: "Hauts-de-France", dept: "59" },
  { slug: "poitiers", name: "Poitiers", region: "Nouvelle-Aquitaine", dept: "86" },
  { slug: "versailles", name: "Versailles", region: "\u00cele-de-France", dept: "78" },
  { slug: "courbevoie", name: "Courbevoie", region: "\u00cele-de-France", dept: "92" },
  { slug: "colombes", name: "Colombes", region: "\u00cele-de-France", dept: "92" },
  { slug: "pau", name: "Pau", region: "Nouvelle-Aquitaine", dept: "64" },
  { slug: "antibes", name: "Antibes", region: "Provence-Alpes-C\u00f4te d'Azur", dept: "06" },
  { slug: "la-rochelle", name: "La Rochelle", region: "Nouvelle-Aquitaine", dept: "17" },
  { slug: "cannes", name: "Cannes", region: "Provence-Alpes-C\u00f4te d'Azur", dept: "06" },
  { slug: "calais", name: "Calais", region: "Hauts-de-France", dept: "62" },
  { slug: "beziers", name: "B\u00e9ziers", region: "Occitanie", dept: "34" },
  { slug: "colmar", name: "Colmar", region: "Grand Est", dept: "68" },
  { slug: "bourges", name: "Bourges", region: "Centre-Val de Loire", dept: "18" },
  { slug: "merignac", name: "M\u00e9rignac", region: "Nouvelle-Aquitaine", dept: "33" },
  { slug: "saint-nazaire", name: "Saint-Nazaire", region: "Pays de la Loire", dept: "44" },
  { slug: "issy-les-moulineaux", name: "Issy-les-Moulineaux", region: "\u00cele-de-France", dept: "92" },
  { slug: "noisy-le-grand", name: "Noisy-le-Grand", region: "\u00cele-de-France", dept: "93" },
  { slug: "villeneuve-d-ascq", name: "Villeneuve-d'Ascq", region: "Hauts-de-France", dept: "59" },
  { slug: "evreux", name: "\u00c9vreux", region: "Normandie", dept: "27" },
  { slug: "quimper", name: "Quimper", region: "Bretagne", dept: "29" },
  { slug: "la-seyne-sur-mer", name: "La Seyne-sur-Mer", region: "Provence-Alpes-C\u00f4te d'Azur", dept: "83" },
  { slug: "antony", name: "Antony", region: "\u00cele-de-France", dept: "92" },
  { slug: "troyes", name: "Troyes", region: "Grand Est", dept: "10" },
  { slug: "neuilly-sur-seine", name: "Neuilly-sur-Seine", region: "\u00cele-de-France", dept: "92" },
  { slug: "lorient", name: "Lorient", region: "Bretagne", dept: "56" },
  { slug: "montauban", name: "Montauban", region: "Occitanie", dept: "82" },
  { slug: "niort", name: "Niort", region: "Nouvelle-Aquitaine", dept: "79" },
  { slug: "chambery", name: "Chamb\u00e9ry", region: "Auvergne-Rh\u00f4ne-Alpes", dept: "73" },
  { slug: "saint-quentin", name: "Saint-Quentin", region: "Hauts-de-France", dept: "02" },
  { slug: "beauvais", name: "Beauvais", region: "Hauts-de-France", dept: "60" },
  { slug: "venissieux", name: "V\u00e9nissieux", region: "Auvergne-Rh\u00f4ne-Alpes", dept: "69" },
  { slug: "cholet", name: "Cholet", region: "Pays de la Loire", dept: "49" },
  { slug: "hyeres", name: "Hy\u00e8res", region: "Provence-Alpes-C\u00f4te d'Azur", dept: "83" },
  { slug: "vannes", name: "Vannes", region: "Bretagne", dept: "56" },
  { slug: "frejus", name: "Fr\u00e9jus", region: "Provence-Alpes-C\u00f4te d'Azur", dept: "83" },
  { slug: "arles", name: "Arles", region: "Provence-Alpes-C\u00f4te d'Azur", dept: "13" },
  { slug: "bayonne", name: "Bayonne", region: "Nouvelle-Aquitaine", dept: "64" },
  { slug: "saint-brieuc", name: "Saint-Brieuc", region: "Bretagne", dept: "22" },
  { slug: "laval", name: "Laval", region: "Pays de la Loire", dept: "53" },
  { slug: "albi", name: "Albi", region: "Occitanie", dept: "81" },
  { slug: "belfort", name: "Belfort", region: "Bourgogne-Franche-Comt\u00e9", dept: "90" },
  { slug: "evry-courcouronnes", name: "\u00c9vry-Courcouronnes", region: "\u00cele-de-France", dept: "91" },
  { slug: "cergy", name: "Cergy", region: "\u00cele-de-France", dept: "95" },
  { slug: "valence", name: "Valence", region: "Auvergne-Rh\u00f4ne-Alpes", dept: "26" },
  { slug: "angouleme", name: "Angoul\u00eame", region: "Nouvelle-Aquitaine", dept: "16" },
  { slug: "chateauroux", name: "Ch\u00e2teauroux", region: "Centre-Val de Loire", dept: "36" },
  { slug: "chartres", name: "Chartres", region: "Centre-Val de Loire", dept: "28" },
  { slug: "narbonne", name: "Narbonne", region: "Occitanie", dept: "11" },
  { slug: "carcassonne", name: "Carcassonne", region: "Occitanie", dept: "11" },
  { slug: "bastia", name: "Bastia", region: "Corse", dept: "2B" },
  { slug: "ajaccio", name: "Ajaccio", region: "Corse", dept: "2A" },
  { slug: "cherbourg-en-cotentin", name: "Cherbourg-en-Cotentin", region: "Normandie", dept: "50" },
  { slug: "saint-malo", name: "Saint-Malo", region: "Bretagne", dept: "35" },
  { slug: "biarritz", name: "Biarritz", region: "Nouvelle-Aquitaine", dept: "64" },
  { slug: "roanne", name: "Roanne", region: "Auvergne-Rh\u00f4ne-Alpes", dept: "42" },
]
